/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AsrSwitch: typeof import('./components/AsrSwitch.vue')['default']
    ChatHistory: typeof import('./components/ChatHistory.vue')['default']
    ConfirmModal: typeof import('./components/ConfirmModal.vue')['default']
    ImageCanvas: typeof import('./components/ImageCanvas.vue')['default']
    ImageGallery: typeof import('./components/ImageGallery.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusIndicator: typeof import('./components/StatusIndicator.vue')['default']
    ToastContainer: typeof import('./components/ToastContainer.vue')['default']
    UserSettingsDialog: typeof import('./components/UserSettingsDialog.vue')['default']
    VoiceRecorder: typeof import('./components/VoiceRecorder.vue')['default']
  }
}
